exclude: ['Rakefile', 'README.md', '_drafts', 'Gemfile', 'Gemfile.lock']
pygments: true
url: http://mikegriffin.ie
markdown: rdiscount
permalink: /blog/:year:month:day-:title
baseurl: http://mikegriffin.ie/
