title: Mike Griffin
author: Mike Griffin
url: "https://mikegriffin.ie"
baseurl: "/"
permalink: /blog/:year:month:day-:title
exclude: 
  - Rakefile
  - README.md
  - _drafts
  - Gemfile
  - Gemfile.lock
  - test

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
